[package]
name = "webroguev2"
version = "0.1.0"
authors = ["Robert Turner Jr <georob23@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "^1.0.59"
serde_derive = "^1.0.59"

[dependencies.wasm-bindgen]
wasm-bindgen = "^0.2"
features = ["serde-serialize"]
